added prediction-retrodiction refs
ContextLab/CDL-bibliography pull request #51
Opened 2021-02-19 16:00 UTC by xinmingxu

### List of citation keys added (one per line)
Hawk85, 
Dess07, 
HassEtal20, 
PillEtal15,
RichSaxe20, 
MlodBrun14, 
BialEtal01, 
MahrCsib18, 
KostSaxe13, 
JonePash07, 
LangEtal15, 
DemiEtal18, 
Bord08, 
ThorTami20, 
Cove94, 
TamiThor18, 
ChanEtal20, 
CohnEtal20, 
EaglSejn00, 
HirsEcht12

### List of citation keys modified (one per line)

### Other changes (describe)

2021-03-17 03:02 UTC, jeremymanning requested changes
for all entries:
- check/fix formatting of author and editor names ([instructions](https://github.com/ContextLab/CDL-bibliography#verify))

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {David M Eagleman and Terrence J Sejnowski},
correct author formatting...

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {William Bialek and Ilya Nemenman and Naftali Tishby},
author formatting...

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {Jason Jones and Harold Pashler},
author formatting...

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {David B Pillemer and Kristina L Steiner and Kie J Kuwabara and Dorthe Kirkegaard Thomsen and Connie Svob},
formatting

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {Leonard Mlodinow and Todd A Brun},
formatting

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {Jean-Louis Dessalles},
formatting

2021-03-17 03:02 UTC, jeremymanning commented on cdl.bib
> +	Author = {Johannes B Mahr and Gergely Csibra},
formatting

2021-11-08 15:20 UTC, jeremymanning commented
@xinmingxu i'm going to close this request for now (until the conflicts are resolved)

2021-11-08 15:20 UTC, closed without merging

2021-12-06 01:14 UTC, xinmingxu commented
How to correct author formatting automatically? Seems not supported by 'autofix' option.

2021-12-06 01:41 UTC, jeremymanning commented
Have you read the readme file to make sure you've formatted things correctly?  If there's a case the format doesn't handle, you can add a "force" field to the entry and the checker will skip it

2021-12-06 01:44 UTC, xinmingxu commented
I can always correct author formatting manually, but an automatic way to do this will be great (currently the checker doesn't pick up full first name formatting)